---

name: demonix-nvidia

description: Fedora Atomic Superchaged with Nix

base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - scottames/ghostty
        
    install:
      packages:
        - distrobox
        - fastfetch
        - mpv
    remove:
      packages:
        - firefox
        - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        
        install: 
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user 

  - type: signing
